spring.application.name=taco-cloud

# określamy nazwę klasy sterownika który odpowiada za połączenie z bazą danych
spring.datasource.driver-class-name=org.h2.Driver
# nie generuj nowej nazwy za każdym razem
spring.datasource.generate-unique-name=false
# nazwa db, więc również JDBC URL też się zmienił na: jdbc:h2:mem::tacocloud
spring.datasource.name=tacocloud

spring.datasource.url=jdbc:h2:mem:tacocloud
spring.datasource.password=
spring.datasource.username=sa